### ISSUE TITLE
Question: e_header.php

### ISSUE THREAD

**Issue by LaocheXe** [arunshekher/livetime#1]
Wouldn't be easier to add e_header.php and have it load the **e107::js('core', "livestamp/moment.min.js"); and e107::js('core', "livestamp/livestamp.min.js");** so administrators don't have to add them in custom themes?

**Comment by arunshekher** [comment]
@LaocheXe,
Sorry I’m away on vacation now that why the delayed response. To answer your issue I think I assumed the way I used is the standard method to load third party libs, and on top of my head I don’t see why it would cause an issue with custom themes. Please correct me if I’m assuming things wrong.

**Comment by LaocheXe** [comment]
Well I would need to add the two lines into my theme.php - when simply you could just add them into e_header.php in the plugin, which will enable the livestamp on the site without having to modify the theme. Because there is no inline editor for e107 to add into the theme in the admin area, and novice users who don't know how to edit php, this would be easier.

**Comment by arunshekher** [comment]
@LaocheXe You don’t need to add those JavaScript libs manually in a custom theme. They should be loaded automatically by e_footer.php just like e_header.php 

 I’m yet to shift fully into the coding mindset so I might still be overlooking something here, please accept my apologies if I’m not understanding you correctly.
